import { config } from 'dotenv'

config()

process.env.BC_API_SECRET_KEY = process.env.BC_API_SECRET_KEY || 'test-secret'
process.env.BC_SMTP_HOST = process.env.BC_SMTP_HOST || 'smtp.test'
process.env.BC_SMTP_PORT = process.env.BC_SMTP_PORT || '587'
process.env.BC_SMTP_USER = process.env.BC_SMTP_USER || 'user'
process.env.BC_SMTP_PASS = process.env.BC_SMTP_PASS || 'pass'
process.env.BC_SMTP_FROM = process.env.BC_SMTP_FROM || 'no-reply@test'
process.env.BC_CDN_USERS = process.env.BC_CDN_USERS || '/cdn/users'
process.env.BC_CDN_TEMP_USERS = process.env.BC_CDN_TEMP_USERS || '/cdn/temp-users'
process.env.BC_CDN_CARS = process.env.BC_CDN_CARS || '/cdn/cars'
process.env.BC_CDN_TEMP_CARS = process.env.BC_CDN_TEMP_CARS || '/cdn/temp-cars'
process.env.BC_CDN_LOCATIONS = process.env.BC_CDN_LOCATIONS || '/cdn/locations'
process.env.BC_CDN_USERS_API = process.env.BC_CDN_USERS_API || '/cdn/api/users'
process.env.BC_CDN_CARS_API = process.env.BC_CDN_CARS_API || '/cdn/api/cars'
process.env.BC_CDN_LOCATIONS_API = process.env.BC_CDN_LOCATIONS_API || '/cdn/api/locations'
process.env.BC_CDN_TEMP_LOCATIONS = process.env.BC_CDN_TEMP_LOCATIONS || '/cdn/temp-locations'
process.env.BC_CDN_CONTRACTS = process.env.BC_CDN_CONTRACTS || '/cdn/contracts'
process.env.BC_CDN_TEMP_CONTRACTS = process.env.BC_CDN_TEMP_CONTRACTS || '/cdn/temp-contracts'
process.env.BC_CDN_INVOICES = process.env.BC_CDN_INVOICES || '/cdn/invoices'
process.env.BC_BACKEND_HOST = process.env.BC_BACKEND_HOST || 'http://localhost:3000'
process.env.BC_FRONTEND_HOST = process.env.BC_FRONTEND_HOST || 'http://localhost:3001'
process.env.BC_SMS_API_KEY = process.env.BC_SMS_API_KEY || 'sms-api-key'
process.env.BC_SMS_API_URL = process.env.BC_SMS_API_URL || 'https://sms.test/api'
process.env.BC_SMS_SENDER = process.env.BC_SMS_SENDER || 'TEST'
process.env.BC_INFO_EMAIL = process.env.BC_INFO_EMAIL || 'info@test'
process.env.BC_SMS_ACTIVE = process.env.BC_SMS_ACTIVE || 'false'

export {}
