import type { LatLngExpression } from 'leaflet'
import type {
  AdvantageItem,
  NearbyDestination,
  VehicleCategory,
  StatItem,
  HeroContent,
  MapConfig,
  CtaContent,
  LocationLandingPageProps,
} from '@/components/location/LocationLandingPage'

const blogUrl = 'https://blog.plany.tn'

type LocationData = Omit<LocationLandingPageProps, 'slug' | 'title' | 'metaDescription'> & {
  slug: string
  title: string
  metaDescription: string
}

const createVehicleCategories = (city: string, basePrice: number): VehicleCategory[] => [
  {
    name: 'Mini',
    price: basePrice,
    description: `Parfaites pour se glisser dans les ruelles de ${city}, ces citadines consomment peu et se stationnent facilement près des marchés et des hôtels.`,
    features: ['Climatisation', '2 bagages cabine', 'Boîte manuelle'],
  },
  {
    name: 'Midi',
    price: basePrice + 15,
    description: `Les berlines intermédiaires offrent plus d’espace pour les familles en visite à ${city} tout en restant confortables sur les axes régionaux.`,
    features: ['5 places confort', 'Kilométrage flexible', 'Bluetooth'],
  },
  {
    name: 'Maxi',
    price: basePrice + 35,
    description: `Idéals pour explorer les environs de ${city} avec des équipements de loisirs, ces SUV et monospaces gèrent sans stress les longs trajets.`,
    features: ['7 places disponibles', 'Grand coffre', 'Options enfants'],
  },
]

const statsFactory = (city: string, agencies: string, clients: string, rating: string, routes: string): StatItem[] => [
  {
    icon: 'car',
    value: agencies,
    label: 'Agences partenaires',
    description: `Réseau local couvrant les quartiers clés de ${city} pour un retrait rapide.`,
  },
  {
    icon: 'support',
    value: clients,
    label: 'Clients accompagnés',
    description: `Nos équipes Plany assistent voyageurs loisirs et business à ${city}.`,
  },
  {
    icon: 'star',
    value: rating,
    label: 'Note moyenne',
    description: 'Avis vérifiés sur la qualité des véhicules et l’accueil sur place.',
  },
  {
    icon: 'experience',
    value: routes,
    label: 'Itinéraires proposés',
    description: `Suggestions d’excursions depuis ${city} vers les sites incontournables.`,
  },
]

const mapConfig = (position: LatLngExpression, description: string, zoom = 12): MapConfig => ({
  position,
  description,
  zoom,
})

const heroFactory = (city: string, subtitle: string, paragraphs: string[]): HeroContent => ({
  headline: `Location de voiture pas cher à ${city} | Plany`,
  subheading: subtitle,
  paragraphs,
})

const faqIntroFactory = (city: string) => `Toutes les réponses pour préparer votre location de voiture à ${city} avec Plany.`

const ctaFactory = (city: string): CtaContent => ({
  title: `Prêt à rouler vers ${city} avec Plany ?`,
  description: `Comparez les offres locales, sélectionnez vos options et validez votre réservation en ligne. Votre voiture vous attend à ${city} dès votre arrivée.`,
})

const advantagesFactory = (city: string): AdvantageItem[] => [
  {
    icon: 'price',
    title: 'Tarifs maîtrisés',
    description: `Plany négocie des prix clairs avec les loueurs de ${city} pour éviter les frais cachés à la prise en charge.`,
  },
  {
    icon: 'car',
    title: 'Choix de véhicules',
    description: `Citadines, berlines, SUV ou utilitaires : nous couvrons les besoins des voyageurs et professionnels basés à ${city}.`,
  },
  {
    icon: 'support',
    title: 'Assistance 7j/7',
    description: `Une équipe francophone répond à vos questions avant, pendant et après votre location à ${city}.`,
  },
  {
    icon: 'experience',
    title: 'Réservations certifiées',
    description: `Processus digital complet et contrats vérifiés pour prendre la route à ${city} sereinement.`,
  },
]

const nearbyFactory = (city: string, items: NearbyDestination[]): NearbyDestination[] =>
  items.map((item) => ({
    ...item,
    description: `${item.description} Louez votre voiture à ${city} et rejoignez ${item.name} en toute liberté.`,
  }))

const locationData: Record<string, LocationData> = {}

export default locationData
locationData.tunis = {
  city: 'Tunis',
  slug: '/location-voiture-pas-cher-a-tunis',
  title: 'Location voiture pas cher à Tunis | Plany',
  metaDescription:
    'Réservez votre voiture à Tunis au meilleur prix avec Plany. Comparez et choisissez parmi nos véhicules économiques, SUV ou luxe.',
  hero: heroFactory(
    'Tunis',
    'Explorez la capitale tunisienne avec un véhicule qui s’adapte à vos déplacements.',
    [
      'Des affaires à Berges du Lac aux sorties culturelles dans la médina, Plany simplifie la location de voiture à Tunis grâce à une interface fluide et des options flexibles.',
      'Nos agences partenaires couvrent les quartiers stratégiques : aéroport Tunis-Carthage, centre-ville, lac de Tunis ou La Marsa. Une prise en main rapide pour garder le contrôle de votre planning.',
    ],
  ),
  advantages: advantagesFactory('Tunis'),
  nearbyDestinations: nearbyFactory('Tunis', [
    {
      name: 'Hammamet',
      image: '/cover.webp',
      imageAlt: 'Location voiture Hammamet avec Plany.tn – plages et médina',
      link: '/location-voiture-pas-cher-a-hammamet',
      description: 'Rejoignez Hammamet en 45 minutes pour profiter de ses plages animées et de la médina.',
    },
    {
      name: 'Nabeul',
      image: '/location-voiture-nabeul-plages.webp',
      imageAlt: 'Location voiture Nabeul avec Plany.tn – souks et poteries',
      link: '/location-voiture-pas-cher-a-nabeul',
      description: 'Découvrez les ateliers de poterie de Nabeul et les souks remplis d’agrumes.',
    },
    {
      name: 'Bizerte',
      image: '/location-voiture-bizerte-port.webp',
      imageAlt: 'Location voiture Bizerte avec Plany.tn – vieux port et corniche',
      link: '/location-voiture-pas-cher-a-bizerte',
      description: 'Cap sur le vieux port de Bizerte et ses spots de plongée réputés.',
    },
  ]),
  nearbyIntro:
    'Profitez de Tunis comme point de départ pour rayonner sur le nord de la Tunisie. En voiture, les stations balnéaires et les sites culturels restent à portée de main.',
  vehicleIntro:
    'Les voyageurs à Tunis privilégient trois gammes de véhicules : citadine pour le centre, berline confortable pour les trajets professionnels, et SUV pour les escapades vers la côte.',
  vehicleCategories: createVehicleCategories('Tunis', 60),
  map: mapConfig([36.8065, 10.1815], 'Retirez votre voiture à l’aéroport Tunis-Carthage, à Lafayette, au Berges du Lac ou encore dans le quartier des affaires du centre-ville.'),
  stats: statsFactory('Tunis', '120+', '18 500', '4.9/5', '35 circuits'),
  statsIntro:
    'Plany accompagne les voyageurs à Tunis depuis plusieurs années avec un réseau d’agences certifiées et une satisfaction client qui dépasse 95%.',
  faqItems: [
    { question: 'Quels sont les tarifs à Tunis ?', answer: 'À partir de 55 TND selon le véhicule, la durée et les options choisies. Les prix augmentent légèrement en haute saison.' },
    { question: 'Quels types de véhicules disponibles ?', answer: 'SUV, citadines, utilitaires ou berlines premium : les loueurs tunisois proposent des flottes variées et récentes.' },
    { question: 'Peut-on louer pour une journée ?', answer: 'Oui, les locations courte durée sont possibles avec retrait rapide dans les agences du centre ou à l’aéroport.' },
  ],
  faqIntro: faqIntroFactory('Tunis'),
  internalLinks: [
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Tunis'),
  crosslinkIntro: 'Prolongez votre roadtrip en découvrant aussi',
}

locationData.sousse = {
  city: 'Sousse',
  slug: '/location-voiture-pas-cher-a-sousse',
  title: 'Location voiture pas cher à Sousse | Plany',
  metaDescription: 'Réservez une voiture à Sousse facilement sur Plany. Profitez de nos offres économiques et d’une réservation rapide.',
  hero: heroFactory(
    'Sousse',
    'Le Sahel tunisien à votre rythme.',
    [
      'Entre la médina classée UNESCO, Port El Kantaoui et les plages familiales, la voiture reste la meilleure option pour naviguer à Sousse selon vos envies.',
      'Plany compare en temps réel les disponibilités des agences locales pour proposer des offres flexibles, livrées à l’hôtel ou à la gare ferroviaire.',
    ],
  ),
  advantages: advantagesFactory('Sousse'),
  nearbyDestinations: nearbyFactory('Sousse', [
    {
      name: 'Monastir',
      image: '/location-voiture-monastir-ribat.webp',
      imageAlt: 'Location voiture Monastir avec Plany.tn – ribat et marina',
      link: '/location-voiture-pas-cher-a-monastir',
      description: 'Visitez le ribat et la marina de Monastir en moins de trente minutes.',
    },
    {
      name: 'Mahdia',
      image: '/location-voiture-mahdia-plages.webp',
      imageAlt: 'Location voiture Mahdia avec Plany.tn – plages et vieille ville',
      link: '/location-voiture-pas-cher-a-mahdia',
      description: 'Profitez d’une journée détente à Mahdia, réputée pour ses fonds marins.',
    },
    {
      name: 'Hammamet',
      image: '/cover.webp',
      imageAlt: 'Location voiture Hammamet avec Plany.tn – plages et médina',
      link: '/location-voiture-pas-cher-a-hammamet',
      description: 'Promenade le long de la corniche d’Hammamet et découverte de sa médina blanche.',
    },
  ]),
  nearbyIntro:
    'Depuis Sousse, un véhicule vous ouvre la route vers Monastir, Mahdia et l’ensemble du littoral du Sahel. Les trajets se font en moins d’une heure.',
  vehicleIntro:
    'Les voyageurs optent majoritairement pour des citadines faciles à stationner près de la médina ou des SUV confortables pour rejoindre Port El Kantaoui.',
  vehicleCategories: createVehicleCategories('Sousse', 50),
  map: mapConfig([35.8256, 10.636], 'Prise en charge à l’avenue Habib Bourguiba, Port El Kantaoui ou aux hôtels de la zone touristique.'),
  stats: statsFactory('Sousse', '65+', '9 800', '4.8/5', '22 circuits'),
  statsIntro:
    'Des milliers de clients nous font confiance pour leurs vacances à Sousse. Nos partenaires locaux assurent un parc entretenu et des options pour toute la famille.',
  faqItems: [
    { question: 'Quels sont les prix à Sousse ?', answer: 'Les tarifs démarrent dès 50 TND par jour selon la saison, le modèle et la durée de location.' },
    { question: 'Types de véhicules disponibles ?', answer: 'Citadines automatiques, SUV climatisés, véhicules familiaux avec sièges enfants sur demande.' },
    { question: 'Y a-t-il livraison hôtel ?', answer: 'Oui, la plupart des agences proposent un service de livraison à l’hôtel ou résidence.' },
  ],
  faqIntro: faqIntroFactory('Sousse'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Sousse'),
  crosslinkIntro: 'Envie de pousser l’aventure ? Comparez aussi nos offres pour',
}

locationData.sfax = {
  city: 'Sfax',
  slug: '/location-voiture-pas-cher-a-sfax',
  title: 'Location voiture pas cher à Sfax | Plany',
  metaDescription: 'Louez une voiture à Sfax avec Plany à prix mini. Accès rapide aux véhicules disponibles, 100% en ligne.',
  hero: heroFactory(
    'Sfax',
    'La capitale économique se découvre en toute autonomie.',
    [
      'Déplacements professionnels, visites de la médina ou excursion vers Kerkennah : la voiture de location reste l’alliée indispensable à Sfax.',
      'Plany centralise les offres des agences du centre-ville, de l’aéroport Thyna et des zones industrielles pour simplifier vos trajets.',
    ],
  ),
  advantages: advantagesFactory('Sfax'),
  nearbyDestinations: nearbyFactory('Sfax', [
    {
      name: 'Kerkennah',
      image: '/cover.webp',
      imageAlt: 'Location voiture Kerkennah avec Plany.tn – archipel et balades en mer',
      link: '/location-voiture-pas-cher-a-mahdia',
      description: 'Embarquez vers les îles Kerkennah et explorez les plages sauvages après un court trajet routier.',
    },
    {
      name: 'Mahdia',
      image: '/location-voiture-mahdia-plages.webp',
      imageAlt: 'Location voiture Mahdia avec Plany.tn – plages et vieille ville',
      link: '/location-voiture-pas-cher-a-mahdia',
      description: 'Un itinéraire côtier vers Mahdia pour goûter à ses spécialités de poissons.',
    },
    {
      name: 'Kairouan',
      image: '/location-voiture-kairouan.webp',
      imageAlt: 'Location voiture Kairouan avec Plany.tn – médina et mosquée Okba',
      link: '/location-voiture-pas-cher-a-kairouan',
      description: 'Découvrez les mosquées et souks de Kairouan en rejoignant l’intérieur des terres.',
    },
  ]),
  nearbyIntro:
    'Depuis Sfax, partez vers les îles Kerkennah, la côte de Mahdia ou les villages artisanaux de l’arrière-pays. Les routes sont bien entretenues sur l’axe RN1.',
  vehicleIntro:
    'Les flottes locales offrent des diesels économiques pour les longues distances et des utilitaires pour les déplacements professionnels.',
  vehicleCategories: createVehicleCategories('Sfax', 52),
  map: mapConfig([34.7406, 10.7603], 'Choisissez un retrait près de la médina, du port ou directement à l’aéroport Sfax-Thyna.'),
  stats: statsFactory('Sfax', '58+', '7 600', '4.7/5', '18 circuits'),
  statsIntro:
    'Plany accompagne les chefs d’entreprise et voyageurs en transit à Sfax avec un réseau certifié et des véhicules adaptés aux routes du sud.',
  faqItems: [
    { question: 'Quel est le tarif moyen ?', answer: 'Comptez entre 50 et 70 TND par jour selon la période et le type de véhicule réservé via Plany.' },
    { question: 'Réservation depuis l’aéroport ?', answer: 'Oui, les agences partenaires livrent au terminal de l’aéroport Thyna sur créneau défini.' },
    { question: 'Voitures diesel disponibles ?', answer: 'Bien sûr, de nombreuses berlines et utilitaires diesel sont proposés pour optimiser la consommation.' },
  ],
  faqIntro: faqIntroFactory('Sfax'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Sfax'),
  crosslinkIntro: 'Programmez vos prochaines étapes vers',
}
locationData.nabeul = {
  city: 'Nabeul',
  slug: '/location-voiture-pas-cher-a-nabeul',
  title: 'Location voiture pas cher à Nabeul | Plany',
  metaDescription: 'Location de voiture à Nabeul à prix pas cher avec Plany. Large choix, réservation rapide, assistance locale.',
  hero: heroFactory(
    'Nabeul',
    'Capitale de la poterie et des agrumes.',
    [
      'Rues parfumées aux orangers, ateliers de céramique et plages dorées : Nabeul se savoure en voiture pour mieux s’arrêter où bon vous semble.',
      'Plany référence les agences du centre, de la corniche et de la route de Hammamet afin de garantir une prise en charge à quelques minutes de votre hébergement.',
    ],
  ),
  advantages: advantagesFactory('Nabeul'),
  nearbyDestinations: nearbyFactory('Nabeul', [
    {
      name: 'Hammamet',
      image: '/cover.webp',
      imageAlt: 'Location voiture Hammamet avec Plany.tn – plages et médina',
      link: '/location-voiture-pas-cher-a-hammamet',
      description: 'Dégustez un thé à la menthe sur la corniche d’Hammamet après un court trajet.',
    },
    {
      name: 'Korba',
      image: '/cover.webp',
      imageAlt: 'Location voiture Korba avec Plany.tn – plages du Cap Bon',
      link: '/location-voiture-pas-cher-a-sousse',
      description: 'Longue plage sauvage à Korba pour surfer et profiter d’un sable fin.',
    },
    {
      name: 'Tunis',
      image: '/location-voiture-tunis-medina.webp',
      imageAlt: 'Location voiture Tunis avec Plany.tn – médina et Berges du Lac',
      link: '/location-voiture-pas-cher-a-tunis',
      description: 'Une virée culturelle à Tunis pour découvrir musées et rooftops.',
    },
  ]),
  nearbyIntro:
    'La presqu’île du Cap Bon réserve des criques et villages artisanaux accessibles uniquement en voiture. Un véhicule vous permet de sortir des sentiers battus.',
  vehicleIntro:
    'Les familles optent souvent pour des monospaces tandis que les couples privilégient la citadine pour circuler aisément autour de la médina.',
  vehicleCategories: createVehicleCategories('Nabeul', 48),
  map: mapConfig([36.4513, 10.735], 'Points de retrait principaux : avenue Habib Bourguiba, zone industrielle et hôtels balnéaires.'),
  stats: statsFactory('Nabeul', '42+', '5 400', '4.7/5', '16 circuits'),
  statsIntro:
    'Notre présence à Nabeul s’appuie sur des loueurs locaux de confiance avec des véhicules récents et bien entretenus.',
  faqItems: [
    { question: 'Quels sont les lieux à visiter ?', answer: 'Korba, Hammamet et les villages du Cap Bon sont facilement accessibles en voiture de location.' },
    { question: 'Voiture possible en aller-simple ?', answer: 'Oui selon les agences ; indiquez votre ville de restitution dans le formulaire pour connaître les frais.' },
    { question: 'Véhicules disponibles ?', answer: 'Citadines, SUV et familiales sont proposées, certaines avec boîte automatique ou GPS inclus.' },
  ],
  faqIntro: faqIntroFactory('Nabeul'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Nabeul'),
  crosslinkIntro: 'Planifiez aussi un passage par',
}

locationData.monastir = {
  city: 'Monastir',
  slug: '/location-voiture-pas-cher-a-monastir',
  title: 'Location voiture pas cher à Monastir | Plany',
  metaDescription: 'Réservez une voiture à Monastir au meilleur tarif avec Plany. Idéal pour visiter les plages et le centre-ville.',
  hero: heroFactory(
    'Monastir',
    'Ville portuaire aux multiples facettes.',
    [
      'Du ribat historique aux plages familiales, Monastir mérite une exploration en voiture pour jongler entre patrimoine et activités nautiques.',
      'Plany coordonne les agences de l’aéroport Habib Bourguiba, de la corniche et de la marina pour faciliter vos arrivées et départs.',
    ],
  ),
  advantages: advantagesFactory('Monastir'),
  nearbyDestinations: nearbyFactory('Monastir', [
    {
      name: 'Sousse',
      image: '/location-voiture-sousse-unesco.webp',
      imageAlt: 'Location voiture Sousse avec Plany.tn – médina UNESCO et Port El Kantaoui',
      link: '/location-voiture-pas-cher-a-sousse',
      description: 'Rejoignez la médina et Port El Kantaoui pour prolonger votre séjour balnéaire.',
    },
    {
      name: 'Mahdia',
      image: '/location-voiture-mahdia-plages.webp',
      imageAlt: 'Location voiture Mahdia avec Plany.tn – plages et vieille ville',
      link: '/location-voiture-pas-cher-a-mahdia',
      description: 'Halte détente à Mahdia pour un déjeuner face à la mer et une plongée.',
    },
    {
      name: 'Kairouan',
      image: '/location-voiture-kairouan.webp',
      imageAlt: 'Location voiture Kairouan avec Plany.tn – médina et mosquée Okba',
      link: '/location-voiture-pas-cher-a-kairouan',
      description: 'Escapade culturelle à Kairouan entre mosquées et ateliers de tapis.',
    },
  ]),
  nearbyIntro:
    'Monastir est un carrefour idéal pour rejoindre Sousse, Mahdia ou encore les villages typiques du Sahel. Une voiture offre la flexibilité nécessaire pour un itinéraire multi-étapes.',
  vehicleIntro:
    'Les familles apprécient les monospaces climatisés tandis que les couples préfèrent les citadines pour circuler sur la corniche.',
  vehicleCategories: createVehicleCategories('Monastir', 49),
  map: mapConfig([35.7643, 10.8113], 'Retrait possible à la marina, à l’aéroport international et près des grands hôtels.'),
  stats: statsFactory('Monastir', '48+', '6 900', '4.8/5', '20 circuits'),
  statsIntro:
    'Notre réseau monastirien assure des véhicules récents et des services de livraison à l’aéroport Habib Bourguiba.',
  faqItems: [
    { question: 'Est-ce adapté aux familles ?', answer: 'Oui, des monospaces et SUV avec sièges enfants sont disponibles sur demande.' },
    { question: 'Peut-on louer depuis l’aéroport ?', answer: 'Oui, les agences partenaires assurent une livraison directe à l’aéroport Habib Bourguiba.' },
    { question: 'Assurance incluse ?', answer: 'Les formules incluent généralement une assurance de base, avec options tous risques proposées lors de la réservation.' },
  ],
  faqIntro: faqIntroFactory('Monastir'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Monastir'),
  crosslinkIntro: 'Combinez votre séjour avec des étapes vers',
}

locationData.mahdia = {
  city: 'Mahdia',
  slug: '/location-voiture-pas-cher-a-mahdia',
  title: 'Location voiture pas cher à Mahdia | Plany',
  metaDescription: 'Trouvez une voiture à Mahdia dès 60 TND/jour avec Plany. Rapide, pratique, économique.',
  hero: heroFactory(
    'Mahdia',
    'L’évasion balnéaire en douceur.',
    [
      'Mahdia séduit par son ambiance portuaire, ses plages et ses restaurants de poissons. Une voiture permet de passer d’une anse à l’autre sans contrainte.',
      'Plany propose des retraits en centre-ville, près du port et dans les resorts pour simplifier chaque étape de votre séjour.',
    ],
  ),
  advantages: advantagesFactory('Mahdia'),
  nearbyDestinations: nearbyFactory('Mahdia', [
    {
      name: 'Monastir',
      image: '/location-voiture-monastir-ribat.webp',
      imageAlt: 'Location voiture Monastir avec Plany.tn – ribat et marina',
      link: '/location-voiture-pas-cher-a-monastir',
      description: 'Rejoignez Monastir pour visiter le mausolée Bourguiba et la marina.',
    },
    {
      name: 'Sousse',
      image: '/location-voiture-sousse-unesco.webp',
      imageAlt: 'Location voiture Sousse avec Plany.tn – médina UNESCO et Port El Kantaoui',
      link: '/location-voiture-pas-cher-a-sousse',
      description: 'Profitez de l’animation nocturne de Sousse à 1h de route.',
    },
    {
      name: 'El Jem',
      image: '/cover.webp',
      imageAlt: 'Location voiture El Jem avec Plany.tn – amphithéâtre romain',
      link: '/location-voiture-pas-cher-a-kairouan',
      description: 'Explorez l’amphithéâtre romain d’El Jem avant de revenir sur la côte.',
    },
  ]),
  nearbyIntro:
    'Les routes côtières offrent des panoramas splendides vers Monastir et Sousse tandis que l’arrière-pays mène aux villages traditionnels du Sahel.',
  vehicleIntro:
    'Citadines pour se faufiler dans le centre, berlines confortables pour longer la côte et SUV familiaux pour transporter tout le monde à la plage.',
  vehicleCategories: createVehicleCategories('Mahdia', 47),
  map: mapConfig([35.5039, 11.0624], 'Choisissez un retrait près du port, dans les hôtels de la zone touristique ou à la gare de Mahdia.'),
  stats: statsFactory('Mahdia', '36+', '4 100', '4.8/5', '14 circuits'),
  statsIntro:
    'Mahdia mise sur des agences à taille humaine, idéales pour un suivi personnalisé et des options longues durées.',
  faqItems: [
    { question: 'Peut-on louer près de la plage ?', answer: 'Oui, plusieurs agences proposent des retraits et retours directement dans les hôtels en bord de mer.' },
    { question: 'Offres longue durée ?', answer: 'Des remises sont disponibles dès 7 jours et davantage pour les séjours de plusieurs semaines.' },
    { question: 'Voiture avec GPS ?', answer: 'Le GPS ou la connexion CarPlay/Android Auto est proposé en option selon les véhicules.' },
  ],
  faqIntro: faqIntroFactory('Mahdia'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Mahdia'),
  crosslinkIntro: 'Envie d’explorer davantage ? Réservez aussi à',
}
locationData.kairouan = {
  city: 'Kairouan',
  slug: '/location-voiture-pas-cher-a-kairouan',
  title: 'Location voiture pas cher à Kairouan | Plany',
  metaDescription: 'Louez une voiture à Kairouan pour explorer ses sites uniques. Tarifs accessibles, réservation rapide.',
  hero: heroFactory(
    'Kairouan',
    'La cité des Aghlabides à portée de volant.',
    [
      'Mosquées majestueuses, souks parfumés et bassins aghlabides : la voiture vous donne la liberté de visiter Kairouan et son arrière-pays rural.',
      'Plany rassemble les agences proches de la médina, des zones artisanales et de la route de Sousse pour simplifier les déplacements.',
    ],
  ),
  advantages: advantagesFactory('Kairouan'),
  nearbyDestinations: nearbyFactory('Kairouan', [
    {
      name: 'Sousse',
      image: '/location-voiture-sousse-unesco.webp',
      imageAlt: 'Location voiture Sousse avec Plany.tn – médina UNESCO et Port El Kantaoui',
      link: '/location-voiture-pas-cher-a-sousse',
      description: 'Variez entre patrimoine religieux et plages du Sahel le temps d’une journée.',
    },
    {
      name: 'Monastir',
      image: '/location-voiture-monastir-ribat.webp',
      imageAlt: 'Location voiture Monastir avec Plany.tn – ribat et marina',
      link: '/location-voiture-pas-cher-a-monastir',
      description: 'Combinez votre pèlerinage avec une halte au bord de la mer Méditerranée.',
    },
    {
      name: 'El Jem',
      image: '/cover.webp',
      imageAlt: 'Location voiture El Jem avec Plany.tn – amphithéâtre romain',
      link: '/location-voiture-pas-cher-a-mahdia',
      description: 'Découvrez l’imposant amphithéâtre romain avant de rejoindre le littoral.',
    },
  ]),
  nearbyIntro:
    'Une voiture facilite les liaisons entre Kairouan, Sousse et Monastir. Elle permet aussi d’explorer les villages producteurs de tapis et d’huile d’olive environnants.',
  vehicleIntro:
    'Les visiteurs choisissent souvent des berlines ou SUV pour affronter les routes secondaires et transporter des souvenirs artisanaux.',
  vehicleCategories: createVehicleCategories('Kairouan', 46),
  map: mapConfig([35.678, 10.099], 'Retirez votre voiture près de la Grande Mosquée, de la route de Sousse ou à la station de bus interurbains.'),
  stats: statsFactory('Kairouan', '30+', '3 800', '4.6/5', '12 circuits'),
  statsIntro:
    'Plany soutient les artisans kairouanais en proposant des véhicules adaptés aux routes rurales et aux visites culturelles.',
  faqItems: [
    { question: 'Quels lieux touristiques ?', answer: 'Mosquée Okba, bassins aghlabides, mausolée des Trois-Portes et villages d’artisans aux alentours.' },
    { question: 'Voiture possible depuis Sfax ?', answer: 'Oui, optez pour l’option aller simple pour déposer votre véhicule à Kairouan ou Sfax selon votre itinéraire.' },
    { question: 'Location utilitaire possible ?', answer: 'Oui, plusieurs loueurs proposent des utilitaires pour les besoins professionnels ou les déménagements.' },
  ],
  faqIntro: faqIntroFactory('Kairouan'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Kairouan'),
  crosslinkIntro: 'Poursuivez votre itinéraire vers',
}

locationData.djerba = {
  city: 'Djerba',
  slug: '/location-voiture-pas-cher-a-djerba',
  title: 'Location voiture pas cher à Djerba | Plany',
  metaDescription: 'Location voiture à Djerba : profitez de votre séjour avec un véhicule adapté. Offres à partir de 55 TND/jour.',
  hero: heroFactory(
    'Djerba',
    'L’île aux mille expériences.',
    [
      'Pour relier Houmt Souk, Midoun, Guellala ou les plages de Seguia, la voiture est indispensable à Djerba.',
      'Plany collabore avec des loueurs insulaires qui livrent à l’aéroport, au port ou directement à votre résidence de vacances.',
    ],
  ),
  advantages: advantagesFactory('Djerba'),
  nearbyDestinations: nearbyFactory('Djerba', [
    {
      name: 'Zarzis',
      image: '/cover.webp',
      imageAlt: 'Location voiture Zarzis avec Plany.tn – station balnéaire du sud',
      link: '/location-voiture-pas-cher-a-medenine',
      description: 'Découvrez la côte de Zarzis et ses restaurants de fruits de mer.',
    },
    {
      name: 'Matmata',
      image: '/cover.webp',
      imageAlt: 'Location voiture Matmata avec Plany.tn – maisons troglodytes',
      link: '/location-voiture-pas-cher-a-gabes',
      description: 'Plongez dans les habitations troglodytes de Matmata à moins de deux heures.',
    },
    {
      name: 'Douz',
      image: '/cover.webp',
      imageAlt: 'Location voiture Douz avec Plany.tn – portes du désert',
      link: '/location-voiture-pas-cher-a-tozeur',
      description: 'Vivez une excursion saharienne à Douz et ses dunes infinies.',
    },
  ]),
  nearbyIntro:
    'Louer une voiture à Djerba vous donne accès aux plages préservées, aux marchés colorés et aux villages berbères situés à l’intérieur de l’île.',
  vehicleIntro:
    'Citadines automatiques pour la zone touristique, SUV pour explorer les pistes sablonneuses et monospaces familiaux pour transporter tout le monde.',
  vehicleCategories: createVehicleCategories('Djerba', 55),
  map: mapConfig([33.8076, 10.8451], 'Retrait à l’aéroport Djerba-Zarzis, à Houmt Souk, Midoun ou à proximité des resorts.'),
  stats: statsFactory('Djerba', '54+', '8 700', '4.8/5', '24 circuits'),
  statsIntro:
    'Nos partenaires djerbiens assurent une disponibilité élevée même en pleine saison grâce à un parc entretenu.',
  faqItems: [
    { question: 'Quel véhicule pour explorer l’île ?', answer: 'Citadine pour les zones urbaines, SUV pour accéder aux plages isolées ou aux pistes vers Guellala.' },
    { question: 'Assurance tous risques ?', answer: 'Disponible en option selon les loueurs. Vérifiez les couvertures avant de confirmer.' },
    { question: 'Lieux populaires ?', answer: 'Houmt Souk, Midoun, musée de Guellala, synagogues et plages de Seguia sont facilement accessibles.' },
  ],
  faqIntro: faqIntroFactory('Djerba'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Djerba'),
  crosslinkIntro: 'Préparez aussi vos excursions vers',
}

locationData.ariana = {
  city: 'Ariana',
  slug: '/location-voiture-pas-cher-a-ariana',
  title: 'Location voiture pas cher à Ariana | Plany',
  metaDescription: 'Réservez une voiture à Ariana avec Plany. Accès facile, bons prix, service rapide.',
  hero: heroFactory(
    'Ariana',
    'Banlieue verte et dynamique au nord de Tunis.',
    [
      'Entre zones résidentielles calmes et quartiers d’affaires, Ariana nécessite une voiture pour circuler confortablement.',
      'Plany coopère avec des agences situées à Ennasr, Charguia et Jardins d’El Menzah pour vous livrer un véhicule à proximité de votre domicile ou bureau.',
    ],
  ),
  advantages: advantagesFactory('Ariana'),
  nearbyDestinations: nearbyFactory('Ariana', [
    {
      name: 'Tunis',
      image: '/location-voiture-tunis-medina.webp',
      imageAlt: 'Location voiture Tunis avec Plany.tn – médina et Berges du Lac',
      link: '/location-voiture-pas-cher-a-tunis',
      description: 'Profitez d’une virée culturelle au cœur de Tunis et de ses restaurants branchés.',
    },
    {
      name: 'La Marsa',
      image: '/location-voiture-la-marsa.webp',
      imageAlt: 'Location voiture La Marsa avec Plany.tn – corniche et cafés du littoral',
      link: '/location-voiture-pas-cher-a-tunis',
      description: 'Rejoignez les plages et cafés de La Marsa en moins de 20 minutes.',
    },
    {
      name: 'Hammamet',
      image: '/cover.webp',
      imageAlt: 'Location voiture Hammamet avec Plany.tn – plages et médina',
      link: '/location-voiture-pas-cher-a-hammamet',
      description: 'Offrez-vous une parenthèse balnéaire à Hammamet pour le week-end.',
    },
  ]),
  nearbyIntro:
    'Avec une voiture, reliez rapidement Tunis, La Marsa et les zones industrielles environnantes pour vos rendez-vous professionnels ou sorties loisirs.',
  vehicleIntro:
    'Citadines automatiques appréciées pour le trafic urbain, berlines confortables pour les trajets business et SUV pour les familles.',
  vehicleCategories: createVehicleCategories('Ariana', 49),
  map: mapConfig([36.8665, 10.1647], 'Retrait possible à Ennasr, Menzah 7, Jardins d’El Menzah ou à l’aéroport Tunis-Carthage.'),
  stats: statsFactory('Ariana', '44+', '6 200', '4.8/5', '18 circuits'),
  statsIntro:
    'Ariana accueille de nombreux résidents et bureaux : nos partenaires locaux répondent aux besoins de mobilité quotidienne.',
  faqItems: [
    { question: 'Y a-t-il des agences au centre-ville ?', answer: 'Oui, des points de retrait sont disponibles à Ennasr, Ariana ville et aux Jardins d’El Menzah.' },
    { question: 'Citadines disponibles ?', answer: 'Un large choix de citadines manuelles ou automatiques est proposé pour gérer le trafic urbain.' },
    { question: 'Assistance en ligne ?', answer: 'Notre équipe support Plany reste joignable 7j/7 pour modifier votre réservation ou prolonger votre contrat.' },
  ],
  faqIntro: faqIntroFactory('Ariana'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Ariana'),
  crosslinkIntro: 'Restez mobile sur le Grand Tunis en explorant aussi',
}

locationData['ben-arous'] = {
  city: 'Ben Arous',
  slug: '/location-voiture-pas-cher-a-ben-arous',
  title: 'Location voiture pas cher à Ben Arous | Plany',
  metaDescription: 'Louez une voiture à Ben Arous avec Plany en quelques clics. Disponibilité immédiate.',
  hero: heroFactory(
    'Ben Arous',
    'Porte sud de la capitale.',
    [
      'Les zones industrielles de Ben Arous et les quartiers résidentiels de Mégrine, Radès ou Ezzahra nécessitent un véhicule pour circuler efficacement.',
      'Plany collabore avec des agences proches des gares, du port de Radès et des grands axes vers Tunis et Hammamet.',
    ],
  ),
  advantages: advantagesFactory('Ben Arous'),
  nearbyDestinations: nearbyFactory('Ben Arous', [
    {
      name: 'Tunis',
      image: '/location-voiture-tunis-medina.webp',
      imageAlt: 'Location voiture Tunis avec Plany.tn – médina et Berges du Lac',
      link: '/location-voiture-pas-cher-a-tunis',
      description: 'Rejoignez rapidement le centre de Tunis pour vos rendez-vous business.',
    },
    {
      name: 'Hammamet',
      image: '/cover.webp',
      imageAlt: 'Location voiture Hammamet avec Plany.tn – plages et médina',
      link: '/location-voiture-pas-cher-a-hammamet',
      description: 'Offrez-vous une pause balnéaire sur la côte en empruntant l’autoroute A1.',
    },
    {
      name: 'Zaghouan',
      image: '/location-voiture-zaghouan.webp',
      imageAlt: 'Location voiture Zaghouan avec Plany.tn – djebel et aqueduc romain',
      link: '/location-voiture-pas-cher-a-zaghouan',
      description: 'Partez en randonnée dans le parc national de Zaghouan et visitez le temple des eaux.',
    },
  ]),
  nearbyIntro:
    'La voiture reste le moyen le plus pratique pour relier Ben Arous aux zones portuaires, à Tunis ou aux stations balnéaires voisines.',
  vehicleIntro:
    'Véhicules utilitaires pour les entreprises, citadines économiques pour les résidents et SUV pour les familles en week-end.',
  vehicleCategories: createVehicleCategories('Ben Arous', 48),
  map: mapConfig([36.744, 10.235], 'Retrait près du port de Radès, de Mégrine, Ezzahra ou de la station de train de Ben Arous.'),
  stats: statsFactory('Ben Arous', '38+', '5 900', '4.7/5', '15 circuits'),
  statsIntro:
    'Ben Arous profite d’un maillage d’agences qui connaissent bien les besoins des professionnels comme des habitants.',
  faqItems: [
    { question: 'Peut-on louer pour entreprises ?', answer: 'Oui, des flottes dédiées aux entreprises et services de location longue durée sont disponibles.' },
    { question: 'Y a-t-il des agences ouvertes le week-end ?', answer: 'Plusieurs loueurs assurent des permanences le week-end pour les départs et retours.' },
    { question: 'Livraison possible ?', answer: 'Livraison sur site industriel ou domicile sur demande, selon les partenaires.' },
  ],
  faqIntro: faqIntroFactory('Ben Arous'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Ben Arous'),
  crosslinkIntro: 'Optimisez vos déplacements en consultant aussi',
}
locationData.bizerte = {
  city: 'Bizerte',
  slug: '/location-voiture-pas-cher-a-bizerte',
  title: 'Location voiture pas cher à Bizerte | Plany',
  metaDescription: 'Réservez votre voiture à Bizerte avec Plany. Prix compétitifs, véhicules récents.',
  hero: heroFactory(
    'Bizerte',
    'Entre port de charme et plages sauvages.',
    [
      'Bizerte offre un patrimoine maritime unique, des plages comme Sidi Salem et un arrière-pays verdoyant. La voiture permet de tout explorer.',
      'Plany réunit les agences du centre-ville, de la zone portuaire et de Cap Blanc pour une prise en charge aisée.',
    ],
  ),
  advantages: advantagesFactory('Bizerte'),
  nearbyDestinations: nearbyFactory('Bizerte', [
    {
      name: 'Raf Raf',
      image: '/cover.webp',
      imageAlt: 'Location voiture Raf Raf avec Plany.tn – plage et falaises',
      link: '/location-voiture-pas-cher-a-tunis',
      description: 'Profitez des eaux turquoises de Raf Raf pour une journée farniente.',
    },
    {
      name: 'Tabarka',
      image: '/location-voiture-tabarka.webp',
      imageAlt: 'Location voiture Tabarka avec Plany.tn – fort génois et corail',
      link: '/location-voiture-pas-cher-a-tunis',
      description: 'Cap sur Tabarka pour plonger autour des aiguilles et des fonds marins.',
    },
    {
      name: 'Tunis',
      image: '/location-voiture-tunis-medina.webp',
      imageAlt: 'Location voiture Tunis avec Plany.tn – médina et Berges du Lac',
      link: '/location-voiture-pas-cher-a-tunis',
      description: 'Reliez la capitale en moins d’une heure pour vos rendez-vous.',
    },
  ]),
  nearbyIntro:
    'En voiture, passez rapidement du vieux port aux plages du nord et aux forêts du djebel Ichkeul.',
  vehicleIntro:
    'Citadines pour la médina, berlines confortables pour les trajets Tunis-Bizerte et SUV pour les excursions nature.',
  vehicleCategories: createVehicleCategories('Bizerte', 50),
  map: mapConfig([37.2746, 9.8739], 'Retrait à la marina, à Zarzouna ou dans les stations balnéaires du nord.'),
  stats: statsFactory('Bizerte', '33+', '4 800', '4.7/5', '14 circuits'),
  statsIntro:
    'Plany accompagne les vacanciers et professionnels avec un réseau d’agences locales connaissant parfaitement les routes du nord.',
  faqItems: [
    { question: 'Accès au vieux port en voiture ?', answer: 'Oui, prévoyez un stationnement dans les parkings sécurisés autour du port pour profiter des restaurants.' },
    { question: 'Voiture automatique possible ?', answer: 'Plusieurs loueurs proposent des modèles automatiques pour faciliter la conduite sur les routes côtières.' },
    { question: 'Livraison à domicile ?', answer: 'Disponible dans la plupart des quartiers de Bizerte, sous réserve de préavis.' },
  ],
  faqIntro: faqIntroFactory('Bizerte'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Bizerte'),
  crosslinkIntro: 'Découvrez aussi nos offres à',
}

locationData.gabes = {
  city: 'Gabès',
  slug: '/location-voiture-pas-cher-a-gabes',
  title: 'Location voiture pas cher à Gabès | Plany',
  metaDescription: 'Louez une voiture à Gabès et explorez le sud tunisien avec liberté.',
  hero: heroFactory(
    'Gabès',
    'Carrefour entre mer et désert.',
    [
      'Gabès est la porte d’entrée du sud : oases, plages et villages troglodytes se rejoignent plus facilement avec un véhicule.',
      'Plany couvre les agences situées au centre-ville, à la zone industrielle et sur la route de Matmata pour accompagner votre roadtrip.',
    ],
  ),
  advantages: advantagesFactory('Gabès'),
  nearbyDestinations: nearbyFactory('Gabès', [
    {
      name: 'Matmata',
      image: '/cover.webp',
      imageAlt: 'Location voiture Matmata avec Plany.tn – maisons troglodytes',
      link: '/location-voiture-pas-cher-a-gabes',
      description: 'Visitez les maisons troglodytes de Matmata à moins d’une heure.',
    },
    {
      name: 'Chenini',
      image: '/cover.webp',
      imageAlt: 'Location voiture Chenini avec Plany.tn – village berbère perché',
      link: '/location-voiture-pas-cher-a-medenine',
      description: 'Explorez les ksour berbères de Chenini près de Tataouine.',
    },
    {
      name: 'Djerba',
      image: '/location-voiture-aeroport-djerba.webp',
      imageAlt: 'Location voiture Djerba avec Plany.tn – plages et villages blancs',
      link: '/location-voiture-pas-cher-a-djerba',
      description: 'Traversez le bac de Jorf pour profiter des plages de Djerba.',
    },
  ]),
  nearbyIntro:
    'Une voiture climatisée est indispensable pour relier Gabès aux oasis de montagne, aux plages de Zarat ou aux villages troglodytes.',
  vehicleIntro:
    'SUV et berlines climatisées sont privilégiés pour supporter la chaleur et les longues distances du sud tunisien.',
  vehicleCategories: createVehicleCategories('Gabès', 53),
  map: mapConfig([33.8815, 10.0982], 'Retrait en centre-ville, à la zone industrielle de Ghannouch ou à la gare ferroviaire.'),
  stats: statsFactory('Gabès', '29+', '3 900', '4.6/5', '13 circuits'),
  statsIntro:
    'Notre réseau gabésien propose des options d’assistance renforcée et des véhicules adaptés aux climats chauds.',
  faqItems: [
    { question: 'Quels lieux explorer ?', answer: 'Matmata, Chenini, Douz, plages de Zarat et oasis de Gabès sont très prisés.' },
    { question: 'Véhicules avec clim ?', answer: 'Oui, fortement recommandés pour rouler dans la région de Gabès en été.' },
    { question: 'Livraison à l’hôtel ?', answer: 'Possible selon le loueur ; indiquez votre hébergement lors de la réservation.' },
  ],
  faqIntro: faqIntroFactory('Gabès'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Gabès'),
  crosslinkIntro: 'Programmez vos étapes suivantes à',
}

locationData.gafsa = {
  city: 'Gafsa',
  slug: '/location-voiture-pas-cher-a-gafsa',
  title: 'Location voiture pas cher à Gafsa | Plany',
  metaDescription: 'Réservez une voiture à Gafsa avec Plany. Accès simple et rapide à nos véhicules.',
  hero: heroFactory(
    'Gafsa',
    'Portes des oasis et du sud-ouest.',
    [
      'La région de Gafsa mêle palmeraies, bassins romains et reliefs montagneux. Un véhicule robuste est conseillé.',
      'Plany collabore avec des loueurs situés à Gafsa ville, Metlaoui et sur la route de Tozeur pour couvrir vos besoins.',
    ],
  ),
  advantages: advantagesFactory('Gafsa'),
  nearbyDestinations: nearbyFactory('Gafsa', [
    {
      name: 'Tozeur',
      image: '/location-voiture-tozeur-oasis.webp',
      imageAlt: 'Location voiture Tozeur avec Plany.tn – oasis et palmeraie',
      link: '/location-voiture-pas-cher-a-tozeur',
      description: 'Découvrez les oasis de Tozeur et les décors de Star Wars à Ong Jmel.',
    },
    {
      name: 'Kasserine',
      image: '/location-voiture-kasserine.webp',
      imageAlt: 'Location voiture Kasserine avec Plany.tn – mont Chaambi et nature',
      link: '/location-voiture-pas-cher-a-kasserine',
      description: 'Randonnée sur les hauteurs du Djebel Chambi depuis Kasserine.',
    },
    {
      name: 'Sidi Bouzid',
      image: '/location-voiture-sidi-bouzid.webp',
      imageAlt: 'Location voiture Sidi Bouzid avec Plany.tn – paysages agricoles du centre',
      link: '/location-voiture-pas-cher-a-sidi-bouzid',
      description: 'Parcourez les champs et marchés agricoles de Sidi Bouzid.',
    },
  ]),
  nearbyIntro:
    'Les routes de montagne et les pistes nécessitent un véhicule en bon état : prévoyez un SUV ou 4x4 pour découvrir la région en toute sécurité.',
  vehicleIntro:
    'Berlines et SUV robustes sont privilégiés pour affronter les reliefs et transporter du matériel.',
  vehicleCategories: createVehicleCategories('Gafsa', 54),
  map: mapConfig([34.425, 8.7842], 'Retrait dans le centre-ville de Gafsa, à Metlaoui ou à proximité des gares.'),
  stats: statsFactory('Gafsa', '27+', '3 200', '4.6/5', '11 circuits'),
  statsIntro:
    'Les agences de Gafsa mettent l’accent sur la fiabilité mécanique et l’assistance en zone désertique.',
  faqItems: [
    { question: 'Voitures 4x4 disponibles ?', answer: 'Oui, fortement recommandées pour les pistes montagneuses et désertiques.' },
    { question: 'Tarif journalier moyen ?', answer: 'Environ 60 TND/jour pour une citadine et plus pour un SUV ou 4x4.' },
    { question: 'Prise en charge à Metlaoui ?', answer: 'Possible selon disponibilité ; indiquez votre point de retrait dans la réservation.' },
  ],
  faqIntro: faqIntroFactory('Gafsa'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Gafsa'),
  crosslinkIntro: 'Prolongez votre itinéraire vers',
}
locationData.tozeur = {
  city: 'Tozeur',
  slug: '/location-voiture-pas-cher-a-tozeur',
  title: 'Location voiture pas cher à Tozeur | Plany',
  metaDescription: 'Trouvez une voiture à Tozeur pour vos escapades désertiques avec Plany.',
  hero: heroFactory(
    'Tozeur',
    'Oasis mythique aux portes du Sahara.',
    [
      'Visitez les oasis de montagne, les palmeraies et les décors de cinéma en toute liberté grâce à une voiture de location.',
      'Plany travaille avec des agences basées à l’aéroport de Tozeur-Nefta et dans le centre-ville pour garantir une prise en charge fluide.',
    ],
  ),
  advantages: advantagesFactory('Tozeur'),
  nearbyDestinations: nearbyFactory('Tozeur', [
    {
      name: 'Chebika',
      image: '/cover.webp',
      imageAlt: 'Location voiture Chebika avec Plany.tn – oasis de montagne',
      link: '/location-voiture-pas-cher-a-gafsa',
      description: 'Accédez aux cascades de Chebika et aux panoramas sur le désert de sel.',
    },
    {
      name: 'Douz',
      image: '/cover.webp',
      imageAlt: 'Location voiture Douz avec Plany.tn – portes du désert',
      link: '/location-voiture-pas-cher-a-gabes',
      description: 'Partez en randonnée dromadaire depuis Douz, la porte du désert.',
    },
    {
      name: 'Chott El Jerid',
      image: '/cover.webp',
      imageAlt: 'Location voiture Chott El Jerid avec Plany.tn – lac salé du sud',
      link: '/location-voiture-pas-cher-a-djerba',
      description: 'Traversez le lac salé au lever du soleil pour une expérience inoubliable.',
    },
  ]),
  nearbyIntro:
    'La voiture est indispensable pour rayonner entre les oasis, les villages troglodytes et le désert autour de Tozeur.',
  vehicleIntro:
    'Privilégiez un SUV ou un 4x4 pour rouler confortablement sur les pistes sablonneuses. Les citadines conviennent aux trajets urbains.',
  vehicleCategories: createVehicleCategories('Tozeur', 56),
  map: mapConfig([33.92, 8.1336], 'Retrait à l’aéroport Tozeur-Nefta, au centre-ville ou près des hôtels de la zone touristique.'),
  stats: statsFactory('Tozeur', '31+', '4 000', '4.7/5', '15 circuits'),
  statsIntro:
    'Nos partenaires tozeuriens connaissent parfaitement les routes sahariennes et fournissent des équipements adaptés (sangles, roue de secours).',
  faqItems: [
    { question: 'Voitures climatisées ?', answer: 'Oui, c’est indispensable pour rouler dans le sud tunisien en été.' },
    { question: 'Routes touristiques accessibles ?', answer: 'Les routes vers Chebika, Tamerza, Midès et Douz sont praticables avec un SUV bien entretenu.' },
    { question: 'Guides disponibles ?', answer: 'Sur demande, certaines agences proposent un chauffeur guide pour les excursions sahariennes.' },
  ],
  faqIntro: faqIntroFactory('Tozeur'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Tozeur'),
  crosslinkIntro: 'Continuez vos aventures sahariennes vers',
}

locationData.kasserine = {
  city: 'Kasserine',
  slug: '/location-voiture-pas-cher-a-kasserine',
  title: 'Location voiture pas cher à Kasserine | Plany',
  metaDescription: 'Louez une voiture à Kasserine facilement avec Plany. Parfait pour les déplacements régionaux.',
  hero: heroFactory(
    'Kasserine',
    'Reliefs montagneux et patrimoine romain.',
    [
      'Kasserine est entourée de montagnes, de sites romains et de forêts. Un véhicule vous aide à rejoindre les villages reculés.',
      'Plany s’appuie sur des agences locales qui livrent à Kasserine ville, Thala ou Feriana pour répondre aux besoins des habitants et professionnels.',
    ],
  ),
  advantages: advantagesFactory('Kasserine'),
  nearbyDestinations: nearbyFactory('Kasserine', [
    {
      name: 'Gafsa',
      image: '/location-voiture-gafsa.webp',
      imageAlt: 'Location voiture Gafsa avec Plany.tn – oasis et bassin romain',
      link: '/location-voiture-pas-cher-a-gafsa',
      description: 'Découvrez les bassins romains de Gafsa et les gorges de Selja.',
    },
    {
      name: 'Sbeitla',
      image: '/cover.webp',
      imageAlt: 'Location voiture Sbeitla avec Plany.tn – ruines romaines',
      link: '/location-voiture-pas-cher-a-sidi-bouzid',
      description: 'Visitez les ruines romaines de Sbeitla et leurs mosaïques intactes.',
    },
    {
      name: 'Le Kef',
      image: '/location-voiture-el-kef.webp',
      imageAlt: 'Location voiture Le Kef avec Plany.tn – kasbah et montagnes',
      link: '/location-voiture-pas-cher-a-tunis',
      description: 'Randonnez dans la région du Kef et découvrez ses vestiges byzantins.',
    },
  ]),
  nearbyIntro:
    'Les reliefs de Kasserine nécessitent un véhicule fiable pour parcourir les routes sinueuses et accéder aux sites historiques.',
  vehicleIntro:
    'SUV et pick-up sont privilégiés pour monter vers le Djebel Chambi, tandis que les citadines conviennent aux trajets urbains.',
  vehicleCategories: createVehicleCategories('Kasserine', 51),
  map: mapConfig([35.1676, 8.8365], 'Retrait à Kasserine centre, à Thala et dans les zones industrielles environnantes.'),
  stats: statsFactory('Kasserine', '24+', '2 900', '4.5/5', '10 circuits'),
  statsIntro:
    'Les agences de Kasserine misent sur des véhicules solides et un service d’assistance renforcé pour les zones montagneuses.',
  faqItems: [
    { question: 'Quels modèles adaptés à la région ?', answer: 'SUV ou 4x4 sont recommandés pour les routes de montagne et les pistes rurales.' },
    { question: 'Assurance incluse ?', answer: 'Les contrats incluent une couverture de base avec option tous risques disponible.' },
    { question: 'Livraison possible ?', answer: 'Livraison à domicile ou en entreprise proposée selon l’agence partenaire.' },
  ],
  faqIntro: faqIntroFactory('Kasserine'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Kasserine'),
  crosslinkIntro: 'Poursuivez votre exploration des montagnes vers',
}

locationData['sidi-bouzid'] = {
  city: 'Sidi Bouzid',
  slug: '/location-voiture-pas-cher-a-sidi-bouzid',
  title: 'Location voiture pas cher à Sidi Bouzid | Plany',
  metaDescription: 'Réservez une voiture à Sidi Bouzid avec Plany à tarif compétitif.',
  hero: heroFactory(
    'Sidi Bouzid',
    'Cœur agricole du centre tunisien.',
    [
      'Sidi Bouzid est réputée pour ses marchés agricoles et ses routes rurales. Une voiture facilite la visite des fermes et villages environnants.',
      'Plany collabore avec des loueurs locaux qui livrent dans le centre-ville, à Regueb ou Jelma.',
    ],
  ),
  advantages: advantagesFactory('Sidi Bouzid'),
  nearbyDestinations: nearbyFactory('Sidi Bouzid', [
    {
      name: 'Kairouan',
      image: '/location-voiture-kairouan.webp',
      imageAlt: 'Location voiture Kairouan avec Plany.tn – médina et mosquée Okba',
      link: '/location-voiture-pas-cher-a-kairouan',
      description: 'Découvrez la grande mosquée et les souks artisans de Kairouan.',
    },
    {
      name: 'Gafsa',
      image: '/location-voiture-gafsa.webp',
      imageAlt: 'Location voiture Gafsa avec Plany.tn – oasis et bassin romain',
      link: '/location-voiture-pas-cher-a-gafsa',
      description: 'Explorez les palmeraies de Gafsa et les gorges de Selja.',
    },
    {
      name: 'Kasserine',
      image: '/location-voiture-kasserine.webp',
      imageAlt: 'Location voiture Kasserine avec Plany.tn – mont Chaambi et nature',
      link: '/location-voiture-pas-cher-a-kasserine',
      description: 'Randonnée sur le Djebel Chambi, point culminant de Tunisie.',
    },
  ]),
  nearbyIntro:
    'Une voiture reste essentielle pour parcourir les routes agricoles et rejoindre les marchés hebdomadaires situés dans les villages voisins.',
  vehicleIntro:
    'Les habitants choisissent des citadines robustes ou des pick-up pour transporter des produits agricoles.',
  vehicleCategories: createVehicleCategories('Sidi Bouzid', 45),
  map: mapConfig([35.0382, 9.4841], 'Retrait en centre-ville, à Regueb et Jelma ou sur la route de Kasserine.'),
  stats: statsFactory('Sidi Bouzid', '22+', '2 600', '4.5/5', '9 circuits'),
  statsIntro:
    'Plany accompagne les professionnels agricoles avec des véhicules adaptés aux routes rurales et aux charges légères.',
  faqItems: [
    { question: 'Possibilité de louer pour 2 jours ?', answer: 'Oui, les agences proposent des locations courte durée avec retrait rapide.' },
    { question: 'Voiture diesel dispo ?', answer: 'Disponible sur demande pour optimiser les trajets longue distance.' },
    { question: 'Livraison sur ferme ?', answer: 'Plusieurs partenaires livrent directement sur site agricole après confirmation.' },
  ],
  faqIntro: faqIntroFactory('Sidi Bouzid'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Sidi Bouzid'),
  crosslinkIntro: 'Planifiez vos prochaines haltes vers',
}
locationData.zaghouan = {
  city: 'Zaghouan',
  slug: '/location-voiture-pas-cher-a-zaghouan',
  title: 'Location voiture pas cher à Zaghouan | Plany',
  metaDescription: 'Louez une voiture à Zaghouan au meilleur prix avec Plany.',
  hero: heroFactory(
    'Zaghouan',
    'Ville verte aux portes de Tunis.',
    [
      'Zaghouan est réputée pour son temple des eaux, ses oliveraies et ses sentiers de randonnée. Une voiture est idéale pour parcourir la région.',
      'Plany réunit des agences situées près du centre-ville, de Djebel Zaghouan et de la route de Hammamet pour faciliter votre prise en charge.',
    ],
  ),
  advantages: advantagesFactory('Zaghouan'),
  nearbyDestinations: nearbyFactory('Zaghouan', [
    {
      name: 'Tunis',
      image: '/location-voiture-tunis-medina.webp',
      imageAlt: 'Location voiture Tunis avec Plany.tn – médina et Berges du Lac',
      link: '/location-voiture-pas-cher-a-tunis',
      description: 'Rejoignez la capitale pour vos rendez-vous administratifs ou culturels.',
    },
    {
      name: 'Hammamet',
      image: '/cover.webp',
      imageAlt: 'Location voiture Hammamet avec Plany.tn – plages et médina',
      link: '/location-voiture-pas-cher-a-hammamet',
      description: 'Profitez d’une pause balnéaire à Hammamet à moins de 45 minutes.',
    },
    {
      name: 'Nabeul',
      image: '/location-voiture-nabeul-plages.webp',
      imageAlt: 'Location voiture Nabeul avec Plany.tn – souks et poteries',
      link: '/location-voiture-pas-cher-a-nabeul',
      description: 'Parcourez les marchés artisanaux de Nabeul et ses ateliers de poterie.',
    },
  ]),
  nearbyIntro:
    'Avec une voiture, vous explorez facilement les villages environnants et les panoramas du Djebel Zaghouan.',
  vehicleIntro:
    'Citadines pour la ville, SUV pour les pistes menant aux sentiers de randonnée et berlines pour les trajets vers Tunis.',
  vehicleCategories: createVehicleCategories('Zaghouan', 47),
  map: mapConfig([36.4008, 10.142], 'Retrait au centre-ville, à Bir Mcherga et sur la route menant à Hammamet.'),
  stats: statsFactory('Zaghouan', '20+', '2 100', '4.6/5', '8 circuits'),
  statsIntro:
    'Les agences zaghouanaises proposent des véhicules récents avec options de livraison dans les villages environnants.',
  faqItems: [
    { question: 'Y a-t-il des routes en bon état ?', answer: 'Oui, les axes principaux sont praticables ; des SUV sont recommandés pour les pistes de montagne.' },
    { question: 'Voiture possible sans acompte ?', answer: 'Certaines agences acceptent une caution réduite ; les conditions sont affichées lors de la réservation.' },
    { question: 'Livraison à domicile ?', answer: 'Oui, sur demande dans les communes proches comme Bir Mcherga ou Fahs.' },
  ],
  faqIntro: faqIntroFactory('Zaghouan'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Zaghouan'),
  crosslinkIntro: 'Envie d’autres escapades ? Consultez',
}

locationData.medenine = {
  city: 'Médenine',
  slug: '/location-voiture-pas-cher-a-medenine',
  title: 'Location voiture pas cher à Médenine | Plany',
  metaDescription: 'Réservez à Médenine une voiture avec Plany et partez à la découverte du sud.',
  hero: heroFactory(
    'Médenine',
    'Carrefour stratégique du sud tunisien.',
    [
      'Médenine relie Djerba, Tataouine et le désert. Une voiture est essentielle pour explorer ksour et oasis en toute autonomie.',
      'Plany collabore avec des agences installées à Médenine ville, Ben Gardane et Zarzis pour faciliter vos trajets.',
    ],
  ),
  advantages: advantagesFactory('Médenine'),
  nearbyDestinations: nearbyFactory('Médenine', [
    {
      name: 'Djerba',
      image: '/location-voiture-aeroport-djerba.webp',
      imageAlt: 'Location voiture Djerba avec Plany.tn – plages et villages blancs',
      link: '/location-voiture-pas-cher-a-djerba',
      description: 'Traversez la chaussée romaine pour rejoindre Djerba en moins de 30 minutes.',
    },
    {
      name: 'Tataouine',
      image: '/location-voiture-tataouine.webp',
      imageAlt: 'Location voiture Tataouine avec Plany.tn – ksours et paysages désertiques',
      link: '/location-voiture-pas-cher-a-gabes',
      description: 'Découvrez les ksour troglodytes de Tataouine et ses paysages désertiques.',
    },
    {
      name: 'Zarzis',
      image: '/cover.webp',
      imageAlt: 'Location voiture Zarzis avec Plany.tn – station balnéaire du sud',
      link: '/location-voiture-pas-cher-a-gabes',
      description: 'Profitez des plages de Zarzis et de ses restaurants de fruits de mer.',
    },
  ]),
  nearbyIntro:
    'La voiture permet de rejoindre facilement Djerba, Ben Gardane ou les villages berbères alentours et d’organiser un roadtrip vers le désert.',
  vehicleIntro:
    'SUV climatisés et berlines diesel sont les plus demandés pour couvrir les longues distances du sud tunisien.',
  vehicleCategories: createVehicleCategories('Médenine', 54),
  map: mapConfig([33.3549, 10.5055], 'Retrait dans le centre de Médenine, à Ben Gardane ou à Zarzis selon votre itinéraire.'),
  stats: statsFactory('Médenine', '35+', '4 700', '4.7/5', '16 circuits'),
  statsIntro:
    'Plany garantit des véhicules prêts pour la route et des partenariats solides avec les agences du sud-est.',
  faqItems: [
    { question: 'Voiture automatique possible ?', answer: 'Oui, disponible sur demande, idéale pour les longues routes rectilignes.' },
    { question: 'Zones proches à visiter ?', answer: 'Zarzis, Ben Gardane, Tataouine et Djerba sont accessibles en moins d’une heure.' },
    { question: 'Livraison à l’hôtel ?', answer: 'La plupart des agences livrent sur votre lieu de séjour ou à la gare routière.' },
  ],
  faqIntro: faqIntroFactory('Médenine'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-jerba-midoun',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Médenine'),
  crosslinkIntro: 'Continuez votre itinéraire vers',
}

locationData['jerba-midoun'] = {
  city: 'Jerba Midoun',
  slug: '/location-voiture-pas-cher-a-jerba-midoun',
  title: 'Location voiture pas cher à Jerba Midoun | Plany',
  metaDescription: 'Location de voiture à Jerba Midoun avec Plany dès 55 TND/jour.',
  hero: heroFactory(
    'Jerba Midoun',
    'Station balnéaire incontournable de l’île.',
    [
      'Midoun concentre les resorts et plages les plus réputées de Djerba. Une voiture garantit des transferts rapides entre plages, souks et activités.',
      'Plany propose des retraits à Midoun, Taguermess et sur la route de la zone touristique pour un service sur-mesure.',
    ],
  ),
  advantages: advantagesFactory('Jerba Midoun'),
  nearbyDestinations: nearbyFactory('Jerba Midoun', [
    {
      name: 'Houmt Souk',
      image: '/cover.webp',
      imageAlt: 'Location voiture Houmt Souk avec Plany.tn – souks et port de Djerba',
      link: '/location-voiture-pas-cher-a-djerba',
      description: 'Flânez dans les souks de Houmt Souk et dégustez un poisson grillé.',
    },
    {
      name: 'Guellala',
      image: '/cover.webp',
      imageAlt: 'Location voiture Guellala avec Plany.tn – potiers de Djerba',
      link: '/location-voiture-pas-cher-a-djerba',
      description: 'Découvrez les artisans potiers de Guellala et son musée berbère.',
    },
    {
      name: 'Zarzis',
      image: '/cover.webp',
      imageAlt: 'Location voiture Zarzis avec Plany.tn – station balnéaire du sud',
      link: '/location-voiture-pas-cher-a-gabes',
      description: 'Partez en excursion à Zarzis pour changer de décor balnéaire.',
    },
  ]),
  nearbyIntro:
    'Votre voiture vous permet de multiplier les activités : plages de Seguia, parc Djerba Explore, excursions en quad dans les palmeraies.',
  vehicleIntro:
    'Citadines automatiques et SUV familiaux sont les plus réservés pour profiter des activités estivales sans contrainte.',
  vehicleCategories: createVehicleCategories('Jerba Midoun', 55),
  map: mapConfig([33.8089, 10.9923], 'Retrait dans la zone touristique de Midoun, à Taguermess ou à proximité des hôtels club.'),
  stats: statsFactory('Jerba Midoun', '40+', '7 200', '4.8/5', '18 circuits'),
  statsIntro:
    'Les agences de Midoun garantissent une grande disponibilité en haute saison et des services de transfert hôtel inclus.',
  faqItems: [
    { question: 'Voitures adaptées aux familles ?', answer: 'Oui, monospaces et SUV avec sièges enfants sont disponibles sur demande.' },
    { question: 'Offre week-end dispo ?', answer: 'Des forfaits week-end permettent de profiter des resorts avec kilométrage flexible.' },
    { question: 'Livraison à l’hôtel ?', answer: 'Oui, livraison et récupération au lobby de votre hôtel sont très courantes.' },
  ],
  faqIntro: faqIntroFactory('Jerba Midoun'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-hammamet',
  ],
  blogUrl,
  cta: ctaFactory('Jerba Midoun'),
  crosslinkIntro: 'Prolongez vos vacances à',
}

locationData.hammamet = {
  city: 'Hammamet',
  slug: '/location-voiture-pas-cher-a-hammamet',
  title: 'Location voiture pas cher à Hammamet | Plany',
  metaDescription: 'Louez une voiture à Hammamet pour découvrir la région en toute liberté.',
  hero: heroFactory(
    'Hammamet',
    'Station balnéaire iconique du Cap Bon.',
    [
      'Entre médina blanche, corniche animée et parcs hôteliers, la voiture facilite vos déplacements à Hammamet.',
      'Plany propose des retraits au centre, à Yasmine Hammamet et à l’autoroute A1 pour rejoindre facilement Nabeul ou Enfidha.',
    ],
  ),
  advantages: advantagesFactory('Hammamet'),
  nearbyDestinations: nearbyFactory('Hammamet', [
    {
      name: 'Nabeul',
      image: '/location-voiture-nabeul-plages.webp',
      imageAlt: 'Location voiture Nabeul avec Plany.tn – souks et poteries',
      link: '/location-voiture-pas-cher-a-nabeul',
      description: 'Découvrez les marchés artisanaux et la gastronomie de Nabeul.',
    },
    {
      name: 'Enfidha',
      image: '/location-voiture-aeroport-enfidha.webp',
      imageAlt: 'Location voiture Enfidha avec Plany.tn – aéroport international',
      link: '/location-voiture-pas-cher-a-tunis',
      description: 'Rejoignez l’aéroport international d’Enfidha pour vos arrivées ou départs.',
    },
    {
      name: 'Sousse',
      image: '/location-voiture-sousse-unesco.webp',
      imageAlt: 'Location voiture Sousse avec Plany.tn – médina UNESCO et Port El Kantaoui',
      link: '/location-voiture-pas-cher-a-sousse',
      description: 'Cap sur Sousse pour profiter de Port El Kantaoui et de ses animations nocturnes.',
    },
  ]),
  nearbyIntro:
    'Depuis Hammamet, ralliez rapidement Nabeul, Enfidha et les parcs d’attractions voisins grâce à votre voiture.',
  vehicleIntro:
    'Citadines pour la médina, cabriolets et SUV premium pour un séjour balnéaire chic.',
  vehicleCategories: createVehicleCategories('Hammamet', 52),
  map: mapConfig([36.403, 10.6167], 'Retrait à la médina, à Yasmine Hammamet ou directement sur l’autoroute A1.'),
  stats: statsFactory('Hammamet', '52+', '11 200', '4.9/5', '26 circuits'),
  statsIntro:
    'Hammamet est l’une des destinations les plus demandées : Plany garantit une large flotte et des options premium.',
  faqItems: [
    { question: 'Voiture pour visiter Nabeul ?', answer: 'Oui, trajet de 20 minutes seulement pour rejoindre Nabeul depuis Hammamet.' },
    { question: 'Agence ouverte le dimanche ?', answer: 'Plusieurs agences assurent une permanence dominicale, notamment en haute saison.' },
    { question: 'Livraison hôtel possible ?', answer: 'Oui, livraison directement à votre resort ou villa de location.' },
  ],
  faqIntro: faqIntroFactory('Hammamet'),
  internalLinks: [
    '/location-voiture-pas-cher-a-tunis',
    '/location-voiture-pas-cher-a-sousse',
    '/location-voiture-pas-cher-a-sfax',
    '/location-voiture-pas-cher-a-nabeul',
    '/location-voiture-pas-cher-a-monastir',
    '/location-voiture-pas-cher-a-mahdia',
    '/location-voiture-pas-cher-a-kairouan',
    '/location-voiture-pas-cher-a-djerba',
    '/location-voiture-pas-cher-a-ariana',
    '/location-voiture-pas-cher-a-ben-arous',
    '/location-voiture-pas-cher-a-bizerte',
    '/location-voiture-pas-cher-a-gabes',
    '/location-voiture-pas-cher-a-gafsa',
    '/location-voiture-pas-cher-a-tozeur',
    '/location-voiture-pas-cher-a-kasserine',
    '/location-voiture-pas-cher-a-sidi-bouzid',
    '/location-voiture-pas-cher-a-zaghouan',
    '/location-voiture-pas-cher-a-medenine',
    '/location-voiture-pas-cher-a-jerba-midoun',
  ],
  blogUrl,
  cta: ctaFactory('Hammamet'),
  crosslinkIntro: 'Explorez davantage la côte en visitant',
}
