name: high-season-prices
on:
  schedule:
    # Exécuter chaque mardi à 7h du matin (UTC)
    - cron: '0 7 * * 2'
  workflow_dispatch: # Permet de déclencher manuellement le workflow depuis l'interface GitHub

jobs:
  update-scores:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Call API to high-season-prices
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -X POST \
            -H "x-api-key: $API_KEY" \
            https://api.plany.tn/api/cron/suppliers/high-season-prices?limit=150&mail=true
