name: Notify Review

on:
  schedule:
    # Exécuter chaque jour de la semaine à 8h du matin (UTC)
    - cron: '0 8 * * 1-5'
  workflow_dispatch: # Permet de déclencher manuellement le workflow depuis l'interface GitHub

jobs:
  notify-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Call API to notify review
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -X POST \
            -H "x-api-key: $API_KEY" \
            "https://api.plany.tn/api/cron/suppliers/review?notifySupplier=true&notifyClient=false&days=1&maxNotifications=1&maxEmails=50"
